# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenXLA project

repo_url: https://github.com/openxla/community
repo_name: openxla/community
edit_uri: ""

theme:
  name: material
  logo: website/assets/openxla-logo-white.svg
  logo_alt: OpenXLA project
  favicon: website/assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  font:
    text: Noto
    code: Noto Sans Mono
  custom_dir: docs/website/overrides
  palette:
    - scheme: default
      primary: black

extra_css:
  - website/stylesheets/openxla.css

markdown_extensions:
  - attr_list
  # Allow MD within HTML tags (requires "markdown" tag on outer HTML)
  - md_in_html
  # Enable code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: True

plugins: [] # Empty plugins list merely to disable search
